# Generated by Django 5.2.6 on 2025-09-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_quiz_history_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='quizhistory',
            options={'verbose_name': 'Quiz History', 'verbose_name_plural': 'Quiz Histories'},
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/default_avatar.png', upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='QuizSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.quizcategory')),
            ],
        ),
    ]
