# Generated by Django 5.2.6 on 2025-09-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_quizcategory_options_alter_quizhistory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark Mode'), ('light', 'Light Mode'), ('blue', 'Blue Theme'), ('green', 'Green Theme'), ('purple', 'Purple Theme'), ('quiz', 'Quiz Pattern Theme'), ('pattern', 'Pattern Theme')], default='default', max_length=20),
        ),
    ]
