# Generated by Django 5.2.6 on 2025-09-18 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_date_of_birth_profile_dob_profile_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizsubcategory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='quizcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizsubcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quizsubcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='users.quizcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='quizcategory',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='quizsubcategory',
            unique_together={('user', 'category', 'name')},
        ),
    ]
