# Generated by Django 5.2.6 on 2025-09-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_quizsubcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='created_at',
            new_name='date_taken',
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='score_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
