# Generated by Django 5.2.6 on 2025-09-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_created_at_quiz_date_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='time_limit',
            field=models.IntegerField(default=300),
        ),
    ]
