# Generated by Django 5.2.6 on 2025-10-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_quiz_time_limit_quizhistory_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='categories_selected',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='quizhistory',
            name='subcategories_selected',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('dark', 'Dark'), ('gradient', 'Gradient'), ('animated-stars', 'Animated Stars'), ('confetti', '🎉 Confetti'), ('particles', '✨ Particles'), ('galaxy', 'Galaxy'), ('matrix', 'Matrix'), ('aurora', 'Aurora')], default='default', max_length=20),
        ),
    ]
