# Generated by Django 5.2.6 on 2025-10-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_quizhistory_categories_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_tip_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ai_tip_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
