# Generated by Django 5.2.6 on 2025-10-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_ai_tip_date_profile_ai_tip_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
