# Generated by Django 5.2.6 on 2025-10-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_badge_userbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='tier',
            field=models.CharField(choices=[('bronze', '🥉 Bronze'), ('silver', '🥈 Silver'), ('gold', '🥇 Gold')], default='bronze', max_length=10),
        ),
    ]
